<template>
  <v-app>
    <v-main>
      <Nuxt />
    </v-main>
  </v-app>
</template>

<script>
export default {}
</script>

<style lang="scss">
html {
  font-family: 'Roboto', sans-serif;
}

h1 {
  margin: 0;
  font-size: 72px;
  line-height: 80px;
  font-weight: 600;

  @media only screen and (max-width: 768px) {
    font-size: 48px;
    line-height: 70px;
    font-weight: 400;
  }
}

h2 {
  font-size: 36px;
  line-height: 40px;
  font-weight: 700;

  @media only screen and (max-width: 768px) {
    font-size: 27px;
  }
}

p {
  width: 70%;
  margin-top: 12px;
  margin-right: 0px;
  margin-bottom: 0px;
  font-family: 'Roboto', sans-serif;
  font-size: 24px;
  line-height: 48px;
  font-weight: 300;

  @media only screen and (max-width: 768px) {
    width: 90%;
    font-size: 20px;
    line-height: 36px;
  }
}

a {
  text-decoration: none;

  &.download {
    height: 30px !important;
  }
}

.container {
  max-width: 1440px;
  padding-right: 100px;
  padding-left: 100px;

  @media only screen and (max-width: 768px) {
    padding: 12px 24px;
  }
}

.pointer {
  cursor: pointer;
}

.green-circle {
  height: 15px;
  width: 15px;
  background-color: #4cd264;
  border-radius: 50%;
  margin-right: 10px;
}

.icon {
  width: 30px;
  height: 30px;
  cursor: pointer;
}

button {
  text-transform: lowercase !important;
  font-family: 'Roboto', sans-serif !important;
  font-size: 16px !important;
}

.availability {
  font-size: 14px;
  color: #000;
  font-weight: 500;
  display: flex;
  align-items: center;
}

// Animations

.slide-in-bottom {
  -webkit-animation: slide-in-bottom 1s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: slide-in-bottom 1s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-11-2 15:34:10
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(100px);
    transform: translateY(100px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(100px);
    transform: translateY(100px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
</style>
